objects = main.cpp recoder.h

exe : $(objects)

	g++ -g -I/home/ubuntu/Desktop/sound/playsound-x11/alsa/include -L/home/ubuntu/Desktop/sound/playsound-x11/alsa/lib -lasound -o exe $(objects)

clean:
	rm exe
